name: CI

on:
  push:
    branches:
      - master  # Adjust the branch as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in current directory
        run: ls -R .

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables..."
          echo "NugetApiKey=${{ secrets.TRI_MONTHLY_TEMPO }}" >> $GITHUB_ENV
          echo "Current environment variables:"
          env | grep NugetApiKey || true  # Use || true to prevent failure if the variable is not set Use the || true Command: The line env | grep NugetApiKey || true allows the script to continue even if the grep command fails (if NugetApiKey is not set). This can help you see