name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set NugetApiKey environment variable
        run: echo "NugetApiKey: ${{ secrets.TRI_MONTHLY_TEMPO }}"
        env:
          NugetApiKey: ${{ secrets.TRI_MONTHLY_TEMPO }}

      - name: Set up environment
        env:
          NugetApiKey: ${{ secrets.TRI_MONTHLY_TEMPO }}
        run: bash /workspaces/PersistedAssemblyBuilder.ConsoleApp/.devcontainer/load-env.sh
