name: CI

on:
  push:
    branches:
      - master  # Adjust according to your needs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables..."
          echo "NugetApiKey=${{ secrets.TRI_MONTHLY_TEMPO }}" >> $GITHUB_ENV
          echo "Current environment variables:"
          env | grep NugetApiKey
      
      - name: Run load-env.sh
        run: bash .devcontainer/load-env.sh
