name: CI

on:
  push:
    branches:
      - master  # Adjust the branch as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in workspace
        run: ls -R /workspaces/PersistedAssemblyBuilder.ConsoleApp/

      - name: Set up environment
        run: bash .devcontainer/load-env.sh
        env:
          NugetApiKey: ${{ secrets.TRI_MONTHLY_TEMPO }}
