name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set NugetApiKey environment variable
        env:
          NugetApiKey: ${{ secrets.TRI_MONTHLY_TEMPO }}  # Set the environment variable using the secret
        run: echo "NugetApiKey is set"  # Just a confirmation message, do not print the actual key

      - name: Set up environment
        env:
          NugetApiKey: ${{ secrets.TRI_MONTHLY_TEMPO }}  # Use the secret for the next command
        run: bash /workspaces/PersistedAssemblyBuilder.ConsoleApp/.devcontainer/load-env.sh
