name: CI

on:
  push:
    branches:
      - master  # Adjust the branch as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in current directory
        run: ls -R .

      - name: Set up environment
        run: |
          echo "Setting up environment variables..."
          echo "NugetApiKey=${{ secrets.TRI_MONTHLY_TEMPO }}" >> $GITHUB_ENV
          bash .devcontainer/load-env.sh
