name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        env:
          NugetApiKey: ${{ secrets.TRI_MONTHLY_TEMPO }}  # Access the secret here
        run: |
          echo "Running load-env.sh script with NugetApiKey"
          echo "NugetApiKey is set to: $NugetApiKey"  # Avoid printing the actual secret in logs
          bash /workspaces/PersistedAssemblyBuilder.ConsoleApp/.devcontainer/load-env.sh
