name: CI

on:
  push:
    branches:
      - master  # Adjust the branch as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in current directory
        run: ls -R .

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables..."
          echo "NugetApiKey=${{ secrets.TRI_MONTHLY_TEMPO }}" >> $GITHUB_ENV
          echo "Current environment variables:"
          env | grep NugetApiKey || true

      - name: Log secret length
        run: |
          echo "Secret length: ${#NugetApiKey}"  # Now this will work since we've set it to an env variable

      - name: List environment variables
        run: env

      - name: Test NugetApiKey
        run: |
          echo "NugetApiKey is set to: $NugetApiKey"  # Will print the value (or part of it)
      
      - name: Print workspace path
        run: |
          echo "Workspace is located at: $GITHUB_WORKSPACE"

      - name: Check folder permissions
        run: ls -ld "$GITHUB_WORKSPACE/PersistedAssemblyBuilder.ConsoleApp/"
              
      - name: Check .env file existence
        run: ls -l "$GITHUB_WORKSPACE/PersistedAssemblyBuilder.ConsoleApp/PersistedAssemblyBuilder.ConsoleApp/"

      - name: Export environment variables
        run: |
          export $(cat "$GITHUB_WORKSPACE/PersistedAssemblyBuilder.ConsoleApp/PersistedAssemblyBuilder.ConsoleApp/BlazorBundler/.env" | xargs)
          ./load-env.sh
            
      - name: Load environment variables
        run: bash ./.devcontainer/load-env.sh